### ISSUE TITLE
feature request: Make playlist stop after playing individual items

### ISSUE THREAD

**Issue by RabidAnubis** [jeremyevans/aqualung#26]
First off...I love Aqualung! It's the only media player out there that maintains a consistent JACK connection.

Here's my use case.

 I'm a podcaster and I want to use Aqualung as a soundboard to trigger my segment bumpers (just standard wav files). However, instead of continuing to the next item on the playlist, I just want it to stop and wait until I make the next selection. 

Maybe this functionality is available now and I haven't figured it out?

I'm willing to code this myself if it doesn't exist.

**Comment by jeremyevans** [comment]
I don't think this is one of Aqualung's features.  One possible way around this is a long file full of silence between each segment, so that after a segment ends, it plays the silence.  Then we you are ready for the next segment, just choose to go to the next track.

I'm not opposed to adding such a feature, but you'll have to provide a pull request if you want the feature added.  Closing this now as it isn't a bug in Aqualung.

**Comment by bikubi** [comment]
i wish i had subscribed to this issue when i first found it -- before i just hacked a really crude "always stop" functionality. took me way to long to read the next lines where i found `stop_after_current_song`! 3 years of adding 5min silence chunks into the playlist and often forgetting to pause, haha!
thanks, @jeremyevans !
