### ISSUE TITLE
rpmlint reports: E: incorrect-fsf-address

### ISSUE THREAD

**Issue by martinkg** [jeremyevans/aqualung#3]
Hi,

rpmlint reports: E: incorrect-fsf-address in many files. T
[fsf-error.txt](https://github.com/jeremyevans/aqualung/files/343169/fsf-error.txt)
he affected files are appended to a file list.

Please correct them.

Example:
-     59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
- ```
  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
  ```
-    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
-    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA`

Thanks Martin

**Comment by jeremyevans** [comment]
COPYING states:

```
Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
```

As stupid as it may be, the plain language states we are not allowed to change it. Later on in the GPL it talks about what happens if the program is licensed using "GPLv2 or any later version", but I'm not sure that aqualung is licensed for "any later version".  I'm going to leave this up to @tomszilagyi.

**Comment by tomszilagyi** [comment]
I found this: https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address

I think the change is harmless (as long as it changes COPYING to the version 2.0 GPL with correct address, linked from the above wiki entry). I'm open to reviewing and eventually merging a pull request that fixes these warnings.

**Comment by martinkg** [comment]
Thanks for your feedback.
