### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mknepper** [jeremyevans/aqualung#8]
I haven't seen many updates. Any news?

**Comment by tomszilagyi** [comment]
'Dead' is not my favourite word. Aqualung reached 1.0 several years ago and has been in maintenance mode since then. We are not fixing stuff that is not broken, and even if it is, we need some motivation to fix it (starting with a clear exposition). The heydays of Aqualung development are certainly over (that was about 13 years ago), but hey, it works if you want to use it (but you most likely want Spotify instead). More than a decade is a long time in the life of all the people who have been involved with this project, and for the most part we are now interested in other projects (and life in general). If you have stuff to contribute, you are welcome to open a pull request.
